Copy lib-caffe-intel-{master,request}-cpu.
Remove Windows support.

NB: Fails to build due to:
error: variable ‘use_dilation’ set but not used [-Werror=unused-but-set-variable]